# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaveAll
                                 A QGIS plugin
 This plugin saves the qgis project file and all vector and raster layers into a user specified folder. All styles and formatting are saved with each layer, ensuring that they are opened up with the proper style the next time the project is opened.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-07-20
        git sha              : $Format:%H$
        copyright            : (C) 2023 by CaptainDang
        email                : Captaindang@protonmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .save_all_dialog import SaveAllDialog

import os
import os.path
import processing
from qgis.PyQt.QtCore import *
from qgis.PyQt.QtGui import QIcon
from qgis.gui import QgsMessageBar
from PyQt5.QtWidgets import *
from qgis.utils import *
from qgis.core import (
    QgsProject,
    QgsMapLayer,
    QgsVectorFileWriter,
    QgsCoordinateTransformContext,
    QgsRasterFileWriter,
    QgsRasterPipe,
    QgsProcessingFeedback,
    Qgis,
)

class SaveAll:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor."""
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        self.actions = []
        self.menu = self.tr(u'&Save All')
        self.first_start = None

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('SaveAll', message)

    def add_action(self, icon_path, text, callback, enabled_flag=True, add_to_menu=True, add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        icon_path = ':/plugins/save_all/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Run Save All'),
            callback=self.run,
            parent=self.iface.mainWindow()
        )
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&Save All'), action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work."""
        failedSaves = []

        def sanitize(layer_name):
            """Sanitize layer name by replacing special characters with an underscore."""
            forbidden_chars = r'<>:"/\|?*'
            return ''.join(c if c not in forbidden_chars else '_' for c in layer_name)

        project = QgsProject.instance()
        layers = project.mapLayers().values()

        # Check for unique layer names
        unique_names = set()
        non_unique_names = []

        for layer in layers:
            name = layer.name()
            if name in unique_names:
                non_unique_names.append(name)
            else:
                unique_names.add(name)

        if non_unique_names:
            msg_box = QMessageBox()
            msg_box.setIcon(QMessageBox.Warning)
            msg_box.setWindowTitle("Layer Name Conflict")
            msg_box.setText("Two or more layers have the same name, which will lead to unintended effects. "
                            "Please make sure that all layers have different names and try again.\n"
                            "Non-unique layer names: {}".format(", ".join(non_unique_names)))
            msg_box.exec_()
            return

        # Open a dialog to select the folder
        selected_folder = QFileDialog.getExistingDirectory(None, "Select parent folder (Project folder will be saved here):", "")

        if not selected_folder:
            self.iface.messageBar().pushMessage("No folder selected. Please try again.", level=1, duration=9)
            return

        # Ask the user to enter a folder name
        folder_name, ok = QInputDialog.getText(None, "Folder Name", "Enter desired folder name. Use same name (case sensitive) to overwrite previous save:")

        if not ok or not folder_name:
            self.iface.messageBar().pushMessage("No folder name entered. Please try again.", level=1, duration=9)
            return

        # Create the full path for the new folder
        new_folder_path = os.path.join(selected_folder, folder_name)
        if not os.path.exists(new_folder_path):
            os.makedirs(new_folder_path)

        # Save each layer in the project
        for layer in layers:
            layer_name = sanitize(layer.name())
            layer_file_path = os.path.join(new_folder_path, layer_name)
        
            if layer.type() == QgsMapLayer.VectorLayer:
                # Configure SaveVectorOptions for vector layers
                options = QgsVectorFileWriter.SaveVectorOptions()
                options.driverName = "GPKG"  # Default to GeoPackage
                options.fileEncoding = "utf-8"
                options.onlySelectedFeatures = False
        
                # Set symbology export based on layer type
                if layer.dataProvider().storageType() in ["CSV", "ESRI Shapefile"]:
                    # Shapefile and CSV do not support symbology export
                    options.symbologyExport = Qgis.FeatureSymbologyExport.NoSymbology
                else:
                    # GeoPackage and other formats support symbology export
                    options.symbologyExport = Qgis.FeatureSymbologyExport.FeatureSymbology
        
                # Handle specific vector layer types
                if layer.dataProvider().storageType() == "CSV":
                    options.driverName = "CSV"
                    layer_file_path += ".csv"
                elif layer.dataProvider().storageType() == "ESRI Shapefile":
                    options.driverName = "ESRI Shapefile"
                    layer_file_path += ".shp"
                elif layer.dataProvider().storageType() == "LIBKML":
                    options.driverName = "LIBKML"
                    layer_file_path += ".kml"
        
                # Write the vector layer
                result = QgsVectorFileWriter.writeAsVectorFormatV3(
                    layer,
                    layer_file_path,
                    QgsCoordinateTransformContext(),
                    options
                )
        
                # Unpack the result (error code, error message, file path, layer name)
                error, error_message, file_path, layer_name_result = result
        
                if error != QgsVectorFileWriter.NoError:
                    # Use the error message from the result
                    self.iface.messageBar().pushMessage("Failed: ", f"Layer '{layer.name()}' was not saved. Error: {error_message}", level=2)
                    failedSaves.append(layer_name)
                else:
                    # Layer saved successfully
                    self.iface.messageBar().pushMessage("Success: ", f"Layer '{layer.name()}' saved successfully.", level=3, duration=3)
        
            elif layer.type() == QgsMapLayer.RasterLayer:
                # Save raster layers as .tif
                output_file = os.path.join(new_folder_path, layer_name + ".tif")
                file_writer = QgsRasterFileWriter(output_file)
                pipe = QgsRasterPipe()
                provider = layer.dataProvider()
        
                if not pipe.set(provider.clone()):
                    self.iface.messageBar().pushMessage("Failed: ", f"Cannot set pipe provider for layer '{layer.name()}'.", level=2)
                    failedSaves.append(layer_name)
                    continue
        
                file_writer.writeRaster(
                    pipe,
                    provider.xSize(),
                    provider.ySize(),
                    provider.extent(),
                    provider.crs()
                )

        # Notify user of failed saves
        if failedSaves:
            msg_box = QMessageBox()
            msg_box.setIcon(QMessageBox.Critical)
            msg_box.setWindowTitle("Unsaved Layers")
            msg_box.setText("Not all layers were successfully saved. Unsaved Layers: {}".format(", ".join(failedSaves)))
            msg_box.exec_()
        else:
            self.iface.messageBar().pushMessage("Success: ", "All layers saved.", level=3, duration=3)

        # Save the QGIS project file
        project_file_name = folder_name + ".qgs"
        project_file_path = os.path.join(new_folder_path, project_file_name)
        project.write(project_file_path)
        self.iface.messageBar().pushMessage("Success: ", "QGIS project file saved successfully.", level=3)
